### ISSUE TITLE
response to dialog input via command

### ISSUE THREAD

**Issue by AimLike** [cizaquita/FakeSAMP#1]
Hello,

is there a possibility to respond to a dialog with a command in the console or in the config to pass a password dialog?

Greets,

**Comment by cizaquita** [comment]
Hi!

Sure, you need to use the `!diares` command, (dialog response). Usually the firts login dialog is the ID 0 or maybe 1.

**Use**
`!diares <Dialog ID> <Button ID> <Listbox item> <Input response>`
Button ID means 'cancel' or 'confirm' buttons from Dialog. (0 or 1 if has 2 buttons, usually is like that)
Listbox item is for a listbox dialog 😄 

**e.g.** 
`!diares 1 1 1 myPassword`

You need to find the Dialog ID, in Unplayer is the ID 1.

Hope that this can help you 👍
