### ISSUE TITLE
Unhandled exception at 0x0043606E in RakSAMPClient.exe: 0xC0000005: Access violation reading location 0x00000098.

### ISSUE THREAD

**Issue by thisRadu** [cizaquita/FakeSAMP#10]
Hi, any idea why I'm getting this error? 
![image](https://user-images.githubusercontent.com/65829311/204073065-83bd0a29-58a9-4c0e-b1fd-f281453fa225.png)

**Comment by VER7U7** [comment]
Same problem....

**Comment by VER7U7** [comment]
Result: https://github.com/cizaquita/FakeSAMP/issues/11

**Comment by cizaquita** [comment]
Solved, thanks.
