### ISSUE TITLE
Not issue, but suggestion

### ISSUE THREAD

**Issue by PazzOnee** [cizaquita/FakeSAMP#12]
Make client password parameter, to auto login when connection close/ lose

**Comment by cizaquita** [comment]
Hello!

Already exists a config tag with password parameter: `<server nickname="MyNickname" password="">127.0.0.1:7777</server>`

If you mean autologin on gamemode, it depends on DialogBox ID for each server, and exists the command DialogResponse -> `!diares id text`

In this case **!diares id password**


For some others servers the login is just a command like /login password

_it depends on the gamemode._

👍🏼
