### ISSUE TITLE
Open X clients with one exe

### ISSUE THREAD

**Issue by hiwyn** [cizaquita/FakeSAMP#13]
Is it possible to open 10 players in one .exe and all of that uses a command /test for example?
Or do i have to open 10 .exe's to open 10 players?

**Comment by cizaquita** [comment]
Here are some useful commands for you:

!kill: toggle fake kill flooder.
!lag: toggle server lagger.
!spam: toggle reconnect spammer.
**!joinflood: toggle join flooder.
!chatflood: toggle chat flooder.**
!classflood: toggle class selection flooder.
!bulletflood: flood the server with bullet sync packets to the players' positions.

You can modifie the **!joinflood** command to send /test when player connects.
All is possible with coding 😄

For multiple players with one .exe you can:
Use multiple Windows Commands Console (CMD) and execute the .exe file.
Copy and paste the .exe multiple times and execute it.

Greets!

**Comment by hiwyn** [comment]
what this !join flood should do?
i already test it when i see on README.md but i think its not working
when i use it only gets server closed connection and nothing really happen
