### ISSUE TITLE
0.3.7 R2 Auth keys

### ISSUE THREAD

**Issue by Joey251** [cizaquita/FakeSAMP#3]
Are you sure that you updated auth keys for 0.3.7 R2?

**Comment by cizaquita** [comment]
Is not working? Do you have that keys? I don't support this project anymore, but I can do something.
Greets 👍 😄

**Comment by Joey251** [comment]
There is "new algoritam" for auth keys https://github.com/P3ti/RakSAMP/compare/v0.8.6-0.3.7-R2...master . And can you add option to increase or decrease ping for some number? I think ping is clientsided so it should be possible to change.
