### ISSUE TITLE
How to bot can Login/Register ?

### ISSUE THREAD

**Issue by Mr4sR** [cizaquita/FakeSAMP#8]

**Comment by cizaquita** [comment]
It depends on login system the server uses, for example if the login is using Dialog frame, you can use !diares

**Comment by Mr4sR** [comment]
@cizaquita it works, but for 0.3DL server which must download source can't?

**Comment by cizaquita** [comment]
> @cizaquita it works, but for 0.3DL server which must download source can't?

The bot does not need sources, but maybe is the server requiring it?

**Comment by Mr4sR** [comment]
> > @cizaquita it works, but for 0.3DL server which must download source can't?
> 
> The bot does not need sources, but maybe is the server requiring it?

Maybe yes, like when I just entered a server where I haven't downloaded the source, I have to download it first
